kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
  namespace: icp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: glustersc
